# Generated by Django 4.2.1 on 2024-02-02 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='arrow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arrow_nodes', to='forest.node'),
        ),
        migrations.AlterField(
            model_name='node',
            name='base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='base_nodes', to='forest.node'),
        ),
    ]
