# Generated by Django 4.2.1 on 2024-02-05 09:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forest", "0002_folder"),
    ]

    operations = [
        migrations.AddField(
            model_name="node",
            name="folder",
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name="Folder",
        ),
    ]
