# Generated by Django 4.2.1 on 2024-02-05 11:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forest", "0004_node_base"),
    ]

    operations = [
        migrations.AlterField(
            model_name="node",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
